# Generated by Django 5.2.6 on 2025-10-08 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='Уровень')),
                ('name', models.CharField(choices=[('Starter', 'Starter'), ('Junior', 'Junior'), ('Middle', 'Middle'), ('Senior', 'Senior')], verbose_name='Название уровня')),
            ],
            options={
                'verbose_name': 'Уровень подписки',
                'verbose_name_plural': 'Уровни подписки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('hash_particle', models.CharField(max_length=100, verbose_name='Хэш')),
                ('registration_date', models.DateField(verbose_name='Дата регистрации')),
                ('nickname', models.CharField(max_length=50, verbose_name='Никнейм')),
                ('roles', models.CharField(choices=[('Админ', 'Админ'), ('Модератор', 'Модератор'), ('Обычный пользователь', 'Обычный пользователь')], max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id', 'user_name'],
            },
        ),
        migrations.CreateModel(
            name='subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата подписки')),
                ('auto_renewal', models.BooleanField(verbose_name='Авто продление')),
                ('id_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.level', verbose_name='Уровень')),
                ('id_users_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='three', to='first_app.users', verbose_name='На кого подписались')),
                ('id_users_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='For', to='first_app.users', verbose_name='Кто подписался')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название стрима')),
                ('category', models.CharField(choices=[('IRL', 'IRL'), ('CREATION', 'CREATION'), ('ESPORTS', 'ESPORTS'), ('GAMING', 'GAMING'), ('MUSIC AND DJS', 'MUSIC AND DJS'), ('JUST CHATTING', 'JUST CHATTING')], verbose_name='Категрия')),
                ('status', models.CharField(max_length=20, verbose_name='Статус')),
                ('start_time', models.TimeField(verbose_name='Время начала стрима')),
                ('end_time', models.TimeField(verbose_name='Время окончания стрима')),
                ('max_viewers', models.IntegerField(verbose_name='макс. кол. зрителей')),
                ('id_users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first_app.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Стрим',
                'verbose_name_plural': 'Стримы',
            },
        ),
        migrations.CreateModel(
            name='donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='сумма')),
                ('requisites', models.CharField(max_length=24, verbose_name='Реквизиты')),
                ('date', models.DateField(verbose_name='Дата')),
                ('id_users_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='two', to='first_app.users', verbose_name='Кто задонатил')),
                ('id_users_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='One', to='first_app.users', verbose_name='Кому задонатил')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
