# Generated by Django 5.2.6 on 2025-10-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата отписки'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания стрима'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='max_viewers',
            field=models.IntegerField(blank=True, null=True, verbose_name='макс. кол. зрителей'),
        ),
    ]
