# Generated by Django 5.2.7 on 2025-10-24 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_subscriptions_end_date_alter_streams_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streams',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='images-maz/', verbose_name='Обложка'),
        ),
    ]
