# Generated by Django 5.2.7 on 2025-10-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_streams_preview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AddField(
            model_name='donations',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержание доната'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='first_app/static/images-maz/', verbose_name='Обложка'),
        ),
    ]
