# Generated by Django 5.2.7 on 2025-10-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_alter_users_options_donations_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='first_app/static/images-maz/', verbose_name='Автарка'),
        ),
        migrations.AlterField(
            model_name='streams',
            name='status',
            field=models.CharField(choices=[('Транслируется', 'Транслируется'), ('Завершился', 'Завершился')], verbose_name='Статус'),
        ),
    ]
